from typing import Any, Dict, List, Optional, Protocol


class AudioProtocol(Protocol):
    def hablar(self, texto: str) -> None: ...
    def escuchar(self, *args: Any, **kwargs: Any) -> str: ...

class AIProtocol(Protocol):
    def route_command(self, text: str) -> Dict[str, Any]: ...
    def summarize(self, text: str) -> str: ...
    def summarize_session(self, messages: List[Dict[str, Any]]) -> Optional[str]: ...
    def disable_ai(self) -> None: ...

    ia_habilitada: bool
    ollama_habilitado: bool
    nvidia_habilitado: bool
    _models_initialized: bool

class MemoryProtocol(Protocol):
    def guardar(self, rol: str, texto: str) -> None: ...
    def cargar(self) -> List[Dict[str, Any]]: ...
    def guardar_evento(self, source: str, event_type: str, content: str) -> None: ...

class ActionProtocol(Protocol):
    def set_obsidian_mcp(self, mcp: Any) -> None: ...
    def set_ai_service(self, ai_svc: Any) -> None: ...
    def execute(self, config: Dict[str, Any]) -> Any: ...

class TelemetryProtocol(Protocol):
    def send(self, state: str, prompt: str = "", response: str = "") -> None: ...
    def close(self) -> None: ...
